# tests/test_embeddings_integration.py

import pytest
from uuid import uuid4
from fastapi import status

# The fixtures from conftest.py (client, factory helpers) are automatically available.

# ============================================================================
# Test API Endpoint Behavior with Automatic Embeddings
# ============================================================================


def test_create_chunk_without_embedding_generates_one(
    client, create_library_via_api, create_document_via_api, create_chunk_via_api
):
    """
    QA Goal: Verify that POSTing a chunk with only 'text' results in a chunk
    object that has a non-null 'embedding' field, generated by our FakeClient.
    """
    # 1. SETUP
    lib = create_library_via_api()
    doc = create_document_via_api(library_id=lib["id"])

    # 2. ACTION: Create a chunk with only text.
    payload = {"text": "cat"}  # This text is known by our FakeEmbeddingsClient
    created_chunk = create_chunk_via_api(
        library_id=lib["id"], document_id=doc["id"], payload=payload
    )

    # 3. VERIFY
    assert "embedding" in created_chunk
    assert created_chunk["embedding"] is not None

    expected_embedding = [0.1, 0.2, 0.8]
    assert created_chunk["embedding"] == expected_embedding


def test_create_chunk_with_embedding_bypasses_generation(
    client, create_library_via_api, create_document_via_api, create_chunk_via_api
):
    """
    QA Goal: Verify that if a user provides their own embedding, the system
    respects it and does not call the embeddings client.
    """
    # 1. SETUP
    lib = create_library_via_api()
    doc = create_document_via_api(library_id=lib["id"])

    # 2. ACTION: Create a chunk, providing a custom embedding.
    custom_embedding = [0.99, 0.98, 0.97]
    payload = {"text": "some text", "embedding": custom_embedding}
    created_chunk = create_chunk_via_api(
        library_id=lib["id"], document_id=doc["id"], payload=payload
    )

    # 3. VERIFY
    assert "embedding" in created_chunk
    assert created_chunk["embedding"] == custom_embedding


# ============================================================================
# Test Search Correctness with Auto-Generated Embeddings
# ============================================================================


def test_search_works_correctly_with_generated_embeddings(
    client,
    create_library_via_api,
    create_document_via_api,
    create_chunk_via_api,
    create_index_via_api,
):
    """
    QA Goal: An end-to-end test to ensure that auto-generated embeddings can be
    successfully indexed and searched, yielding correct semantic results.
    """
    # 1. SETUP: Create a library and add chunks with text ONLY.
    lib = create_library_via_api()
    doc = create_document_via_api(library_id=lib["id"])

    texts_to_index = ["cat", "dog", "kitten", "puppy", "computer"]
    for text in texts_to_index:
        create_chunk_via_api(
            library_id=lib["id"], document_id=doc["id"], payload={"text": text}
        )

    # 2. CREATE INDEX
    index_name = "auto-embed-index"
    create_index_via_api(
        library_id=lib["id"], index_name=index_name, payload={"index_type": "avl"}
    )

    # 3. SEARCH
    query_vector_for_small_dog = [0.84, 0.26, 0.16]  # Close to "puppy"
    search_payload = {"query_embedding": query_vector_for_small_dog, "k": 2}

    response = client.post(
        f"/libraries/{lib['id']}/search/{index_name}", json=search_payload
    )
    assert response.status_code == status.HTTP_200_OK

    # 4. VERIFY
    results = response.json()
    assert len(results) == 2
    result_texts = [res["chunk"]["text"] for res in results]
    assert result_texts[0] == "puppy"
    assert result_texts[1] == "dog"
